# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
name: R-CMD-check

on:
  push:
    branches: [main, master]
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - 'README.Rmd'
      - 'vignettes/**'
      - '_pkgdown.yml'
      - 'docs/pkgdown.yml'
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - 'README.Rmd'
      - 'vignettes/**'
      - '_pkgdown.yml'
      - 'docs/pkgdown.yml'

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - { os: macos-latest,   r: 'release' }
          - { os: windows-latest, r: 'release' }
          - { os: ubuntu-latest,  r: 'devel' }
          - { os: ubuntu-latest,  r: 'release' }
          - { os: ubuntu-latest,  r: 'oldrel-1' }

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r-dependencies@v2
  with:
    extra-packages: any::rcmdcheck
    needs: check         # <- install Suggests for running tests/vignettes


      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true